### ISSUE TITLE
Increase max offset to enable access to full caselist

### ISSUE THREAD

**Issue by abziegler** [harvard-lil/capstone#457] opened 2018-09-17 12:59 UTC
Offset > 10000 is disallowed, but many lists (e.g. cases) require much higher. We should allow as high an offset as is needed.

Examples: 
https://capapi.org/api/v1/cases/?limit=100&offset=10000
https://capapi.org/api/v1/cases/?limit=100&offset=10100

**Comment by jcushman** [comment] 2018-09-17 13:25
Duplicate of #452

**Closed as completed by jcushman** 2018-09-17 13:25 UTC
Labels: API
