### ISSUE TITLE
Fix boolean logic across opinions

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1981] opened 2021-08-23 17:04 UTC
Switching the cases index to nested elasticsearch documents per opinion had the effect of changing the boolean logic for search queries.

If you do `?search=foo bar`, that should mean "find cases where one of the metadata fields or one of opinions contains 'foo', and one contains 'bar'", but it now means "find cases where one of the metadata fields or one of opinions contains both 'foo' and 'bar'."

The fix is probably to use the `copy_to` attribute on the fields we want to search and copy them to a single elasticsearch column, which would also make the search a little faster. But this needs research because it would also increase the index size, potentially too much for the server.

**Comment by kilbergr** [comment] 2023-03-22 17:19
Comprehension check--
You want the `?search=foo bar` query to return cases where either:
1. one of the metadata fields contains 'foo' and one of opinions contains 'bar'
2. one of the opinions contains 'foo' and one of metadata fields contains 'bar'

Is that right @jcushman ?

**Comment by jcushman** [comment] 2023-03-22 18:04
Good question! Starting from a user experience perspective, the goal would be that if I do an "and" search for foo and bar, such as `?search=foo bar`, and a given case page like cite.case.law/mass/1/1/ shows both the words foo and bar, then the case should match.

Right now elasticsearch is requiring that ANDed terms all appear in the same section of the page, so it'll wrongly fail to return /mass/1/1/ if foo happens to be in one part of the page while bar is in another.

**Comment by kilbergr** [comment] 2023-03-23 17:37
Further clarification from Slack https://hlslil.slack.com/archives/C0JS2FR3J/p1679583130799379
This was not referencing the `CaseMetadata` model, but instead metadata (nested data) in the [CaseDocument model](https://github.com/harvard-lil/capstone/blob/64c3dc16bb6083398a2a32938cf179c27d942657/capstone/capapi/filters.py#L501).
So the issue is: if `foo` shows up in one of those fields and `bar` shows up in an opinion for a case, will that case be returned for the `?search=foo bar` query.

**Comment by kilbergr** [comment] 2023-04-07 15:05
Process for now: close this ticket because we have [a fix](https://github.com/harvard-lil/capstone/pull/2132). Leave the fix open until [the deployment](https://github.com/harvard-lil/capstone/issues/2133) is complete. Have we created a recursion issue creation loop? Only time will tellllllllllll.

**Closed as completed by kilbergr** 2023-04-07 15:05 UTC
Labels: API
